name: Documentation

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    name: ${{ matrix.pkg.name }} Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - name: GeneralisedFilters
            dir: './GeneralisedFilters'
          - name: SSMProblems
            dir: './SSMProblems'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v1

      # Note: We omit an explicit "Install dependencies" step here because
      # the DocsDocumenter composite action itself performs dependency installation.

      # Build and deploy using the updated DocsDocumenter action.
      - name: Build and deploy documentation
        uses: shravanngoswamii/actions/DocsDocumenter@main
        with:
          pkg_path: ${{ matrix.pkg.dir }}
          doc-path: ${{ matrix.pkg.dir }}/docs
          doc-make-path: ${{ matrix.pkg.dir }}/docs/make.jl
          doc-build-path: ${{ matrix.pkg.dir }}/docs/build
          dirname: ${{ matrix.pkg.name }}
          # For GeneralisedFilters, run the pre-build command that overrides SSMProblems.
          pre_build: ${{ matrix.pkg.name == 'GeneralisedFilters' && 'julia --project=./GeneralisedFilters/docs -e "using Pkg; Pkg.develop(PackageSpec(path=\\\"./SSMProblems\\\")); Pkg.instantiate()"' || '' }}
          pre_build_continue_on_error: 'false'
